### ISSUE TITLE
Generated MySQL credentials not updated in rotate script

### ISSUE THREAD

**Issue by credd144** [sipcapture/homer-installer#2]
Using the shell script to install on Debain 8, eventually found that the rotate script wasn't completing as the rotation.ini file still has default homer_user and homer_password in the [MySQL] section.

**Comment by lmangani** [comment]
Patched in ca852c21e4cb3ae17cedff3b66777baacfd5eb6d
Thanks for the report!

**Comment by mbeckwell** [comment]
Even with the newly patched ca852c2, this is still a problem.

It appears that while the bash script is reading the variables sqlhomeruser, sqlhomerpassword, and sqlpassword... they aren't actually replacing the contents of DB_USER/DB_PASS unless $sqlhomeruser and $sqlhomerpassword are blank (lines 235 / 240)

I think we would need something like this around line 227:

read sqlhomeruser
- DB_USER="$sqlhomeruser"

read sqlhomerpassword
- DB_PASS="$sqlhomerpassword"

Otherwise, the perl command is essentially doing this every time (replacing "homer_user" with "homer_user" ,etc. and we're left with the default declared variables on line 43/44).

perl -p -i -e s/homer_user/homer_user/ /opt/homer_rotate
perl -p -i -e s/homer_password/homer_password/ /opt/homer_rotate
perl -p -i -e s/homer_user/homer_user/ /opt/rotation.ini
perl -p -i -e s/homer_password/homer_password/ /opt/rotation.ini

**Comment by lmangani** [comment]
Moved the global declaration to the right placewith  fdf22e2aa3a557cdc50c4516142889c8ed0f95b1
