### ISSUE TITLE
cpio error is never appears

### ISSUE THREAD

**Issue by Pechenn** [sipcapture/homer-installer#41]
+++ command -v cpio
++ valid_cmd=
++ [[ ! -z '' ]]
++ echo 'HALT: Please install package for command '\''cpio'\'''
++ /bin/kill -s TERM 68899
++ exit 1
++ return 0
in normal mod this error is never been echoed

**Comment by 00Asgaroth00** [comment]
This happens because the "locate_cmd" function is run in a subshell and the output (echo) is never received by the calling shell as the locate_cmd function terminates the calling process before it can return anything.

Will need to have a think about how to improve this.

As a workaround running in trace mode will give you all diagnostic info.

```
TRACE=1 ./homer_installer.sh
```
